version: "3.5"

networks:
  default:
    external:
      name: gateway
  databases:
    driver: bridge
    internal: true

services:
  postgresql:
    image: "bitnami/postgresql:latest"
    environment:
      POSTGRESQL_PASSWORD: ${DISCOURSE_PG_ROOT_PASS}
      POSTGRESQL_DATABASE: discourse
    volumes:
      - "${DATA_DIR}/openmp/postgresql:/bitnami"
    networks:
      - databases

  redis:
    image: "bitnami/redis:latest"
    environment:
      ALLOW_EMPTY_PASSWORD: "no"
      DISABLE_COMMANDS: "FLUSHDB,FLUSHALL,CONFIG"
      REDIS_HOST: redis # Hostname for Redis.
      REDIS_PORT_NUMBER: "6379" # Port used by Redis.
      REDIS_PASSWORD: ${DISCOURSE_REDIS_PASS} # Password for Redis.
    volumes:
      - "${DATA_DIR}/openmp/redis:/bitnami"
    networks:
      - databases

  sidekiq:
    image: "bitnami/discourse:latest"
    command: "nami start --foreground discourse-sidekiq"
    environment:
      DISCOURSE_POSTGRESQL_NAME: discourse
      DISCOURSE_POSTGRESQL_USERNAME: postgres
      DISCOURSE_POSTGRESQL_PASSWORD: ${DISCOURSE_PG_PASS}
      DISCOURSE_HOST: discourse
      DISCOURSE_PORT: 3000
      DISCOURSE_HOSTNAME: forum.southcla.ws
      REDIS_HOST: redis # Hostname for Redis.
      REDIS_PORT_NUMBER: "6379" # Port used by Redis.
      REDIS_PASSWORD: ${DISCOURSE_REDIS_PASS} # Password for Redis.
    volumes:
      - "${DATA_DIR}/openmp/sidekiq:/bitnami"
    networks:
      - databases
    depends_on:
      - discourse

  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: forum.southcla.ws
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ${DATA_DIR}/openmp/maildata:/var/mail
      - ${DATA_DIR}/openmp/mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
    environment:
      - DMS_DEBUG=${DMS_DEBUG}
      - ENABLE_CLAMAV=${ENABLE_CLAMAV}
      - ONE_DIR=${ONE_DIR}
      - ENABLE_POP3=${ENABLE_POP3}
      - ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
      - ENABLE_MANAGESIEVE=${ENABLE_MANAGESIEVE}
      - OVERRIDE_HOSTNAME=${OVERRIDE_HOSTNAME}
      - POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
      - POSTSCREEN_ACTION=${POSTSCREEN_ACTION}
      - REPORT_RECIPIENT=${REPORT_RECIPIENT}
      - REPORT_SENDER=${REPORT_SENDER}
      - REPORT_INTERVAL=${REPORT_INTERVAL}
      - SMTP_ONLY=${SMTP_ONLY}
      - SSL_TYPE=${SSL_TYPE}
      - TLS_LEVEL=${TLS_LEVEL}
      - SPOOF_PROTECTION=${SPOOF_PROTECTION}
      - ENABLE_SRS=${ENABLE_SRS}
      - PERMIT_DOCKER=${PERMIT_DOCKER}
      - VIRUSMAILS_DELETE_DELAY=${VIRUSMAILS_DELETE_DELAY}
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=${ENABLE_POSTFIX_VIRTUAL_TRANSPORT}
      - POSTFIX_DAGENT=${POSTFIX_DAGENT}
      - ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
      - SA_TAG=${SA_TAG}
      - SA_TAG2=${SA_TAG2}
      - SA_KILL=${SA_KILL}
      - SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT}
      - ENABLE_FETCHMAIL=${ENABLE_FETCHMAIL}
      - FETCHMAIL_POLL=${FETCHMAIL_POLL}
      - ENABLE_LDAP=${ENABLE_LDAP}
      - LDAP_START_TLS=${LDAP_START_TLS}
      - LDAP_SERVER_HOST=${LDAP_SERVER_HOST}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PW=${LDAP_BIND_PW}
      - LDAP_QUERY_FILTER_USER=${LDAP_QUERY_FILTER_USER}
      - LDAP_QUERY_FILTER_GROUP=${LDAP_QUERY_FILTER_GROUP}
      - LDAP_QUERY_FILTER_ALIAS=${LDAP_QUERY_FILTER_ALIAS}
      - DOVECOT_TLS=${DOVECOT_TLS}
      - DOVECOT_USER_FILTER=${DOVECOT_USER_FILTER}
      - DOVECOT_PASS_FILTER=${DOVECOT_PASS_FILTER}
      - ENABLE_POSTGREY=${ENABLE_POSTGREY}
      - POSTGREY_DELAY=${POSTGREY_DELAY}
      - POSTGREY_MAX_AGE=${POSTGREY_MAX_AGE}
      - POSTGREY_TEXT=${POSTGREY_TEXT}
      - ENABLE_SASLAUTHD=${ENABLE_SASLAUTHD}
      - SASLAUTHD_MECHANISMS=${SASLAUTHD_MECHANISMS}
      - SASLAUTHD_MECH_OPTIONS=${SASLAUTHD_MECH_OPTIONS}
      - SASLAUTHD_LDAP_SERVER=${SASLAUTHD_LDAP_SERVER}
      - SASLAUTHD_LDAP_SSL=${SASLAUTHD_LDAP_SSL}
      - SASLAUTHD_LDAP_BIND_DN=${SASLAUTHD_LDAP_BIND_DN}
      - SASLAUTHD_LDAP_PASSWORD=${SASLAUTHD_LDAP_PASSWORD}
      - SASLAUTHD_LDAP_SEARCH_BASE=${SASLAUTHD_LDAP_SEARCH_BASE}
      - SASLAUTHD_LDAP_FILTER=${SASLAUTHD_LDAP_FILTER}
      - SASLAUTHD_LDAP_START_TLS=${SASLAUTHD_LDAP_START_TLS}
      - SASLAUTHD_LDAP_TLS_CHECK_PEER=${SASLAUTHD_LDAP_TLS_CHECK_PEER}
      - SASL_PASSWD=${SASL_PASSWD}
      - SRS_EXCLUDE_DOMAINS=${SRS_EXCLUDE_DOMAINS}
      - SRS_SECRET=${SRS_SECRET}
      - RELAY_HOST=${RELAY_HOST}
      - RELAY_PORT=${RELAY_PORT}
      - RELAY_USER=${RELAY_USER}
      - RELAY_PASSWORD=${RELAY_PASSWORD}
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
    networks:
      - default
      - databases

  discourse:
    image: "bitnami/discourse:latest"
    environment:
      DISCOURSE_USERNAME: root # Discourse application username.
      DISCOURSE_PASSWORD: ${DISCOURSE_ROOT_PASS} # Discourse application password.
      DISCOURSE_EMAIL: admin@southcla.ws # Discourse application email.
      DISCOURSE_SITENAME: Southclaws # Discourse site name.
      DISCOURSE_HOSTNAME: forum.southcla.ws # Discourse hostname to create application URLs for features such as email notifications and emojis. It can be either an IP or a domain.
      POSTGRESQL_ROOT_USER: postgres # Root user for the Postgresql database.
      POSTGRESQL_ROOT_PASSWORD: ${DISCOURSE_PG_ROOT_PASS} # Root password for Postgresql.
      POSTGRESQL_HOST: postgresql # Hostname for Postgresql server.
      POSTGRESQL_PORT_NUMBER: "5432" # Port used by Postgresql server.
      DISCOURSE_POSTGRESQL_USERNAME: postgres # Discourse application database user. bn_discourse
      DISCOURSE_POSTGRESQL_PASSWORD: ${DISCOURSE_PG_PASS} # Discourse application database password. bitnami1
      DISCOURSE_POSTGRESQL_NAME: discourse # Discourse application database name. bitnami_application
      POSTGRESQL_CLIENT_CREATE_DATABASE_NAME: discourse # unknown...
      POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME: discourse # unknown...
      POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD: ${DISCOURSE_PG_PASS} # unknown...
      REDIS_HOST: redis # Hostname for Redis.
      REDIS_PORT_NUMBER: "6379" # Port used by Redis.
      REDIS_PASSWORD: ${DISCOURSE_REDIS_PASS} # Password for Redis.
      SMTP_HOST: mail # Host for outgoing SMTP email.
      SMTP_PORT: "587" # Port for outgoing SMTP email.
      SMTP_USER: admin@forum.southcla.ws # User of SMTP used for authentication (likely email).
      SMTP_PASSWORD: ${DISCOURSE_SMTP_PASS} # Password for SMTP.
      SMTP_TLS: "true" # Whether use TLS protocol for SMTP or not.
    ports:
      - "80:3000"
    volumes:
      - "${DATA_DIR}/openmp/discourse:/bitnami"
    networks:
      - default
      - databases
    depends_on:
      - mail
      - postgresql
      - redis
