version: "3.5"

networks:
    default:
        external:
            name: gateway
    database:
        driver: bridge
        internal: true

services:
    mybb:
        image: mybb/mybb:latest
        volumes:
            - ${DATA_DIR}/burgershot/mybb:/var/www/html
        networks:
            - default
            - database
        labels:
            - traefik.docker.network=gateway
            - traefik.frontend.rule=Host:burgershot.gg
            - traefik.frontend.headers.SSLRedirect=false
            - traefik.port=9000

    postgresql:
        image: postgres:10.4
        environment:
            POSTGRES_DB: burgershot
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: burgershot
        networks:
            - database
        volumes:
            - ${DATA_DIR}/burgershot/postgres/data:/var/lib/postgresql/data
