version: "3.5"

networks:
    default:
        external:
            name: gateway
    databases:
        driver: bridge
        internal: true

services:
    postgresql:
        image: "bitnami/postgresql:latest"
        restart: on-failure
        environment:
            POSTGRESQL_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRESQL_DATABASE: discourse
        volumes:
            - "${DATA_DIR}/openmp/postgresql:/bitnami"
        networks:
            - databases
        labels:
            - traefik.enable=false

    redis:
        image: "bitnami/redis:latest"
        restart: on-failure
        environment:
            ALLOW_EMPTY_PASSWORD: "no"
            DISABLE_COMMANDS: "FLUSHDB,FLUSHALL,CONFIG"
            REDIS_HOST: redis # Hostname for Redis.
            REDIS_PORT_NUMBER: "6379" # Port used by Redis.
            REDIS_PASSWORD: ${REDIS_PASSWORD} # Password for Redis.
        volumes:
            - "${DATA_DIR}/openmp/redis:/bitnami"
        networks:
            - databases
        labels:
            - traefik.enable=false

    sidekiq:
        image: "bitnami/discourse:2.0.5"
        command: "nami start --foreground discourse-sidekiq"
        restart: on-failure
        environment:
            POSTGRESQL_ROOT_USER: postgres
            POSTGRESQL_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRESQL_HOST: postgresql
            POSTGRESQL_PORT_NUMBER: "5432"
            DISCOURSE_POSTGRESQL_USERNAME: postgres
            DISCOURSE_POSTGRESQL_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            DISCOURSE_POSTGRESQL_NAME: discourse
            DISCOURSE_HOST: discourse
            DISCOURSE_PORT: 3000
            DISCOURSE_HOSTNAME: forum.southcla.ws
            REDIS_HOST: redis
            REDIS_PORT_NUMBER: "6379"
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            SMTP_HOST: ${SMTP_HOSTNAME}
            SMTP_PORT: "${SMTP_PORT}"
            SMTP_USER: ${SMTP_USERNAME}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            SMTP_TLS: "${SMTP_USE_TLS}"
        volumes:
            - "${DATA_DIR}/openmp/sidekiq:/bitnami"
        networks:
            - databases
        depends_on:
            - discourse
        labels:
            - traefik.enable=false

    discourse:
        image: "bitnami/discourse:2.0.5"
        restart: on-failure
        environment:
            DISCOURSE_USERNAME: root
            DISCOURSE_PASSWORD: ${DISCOURSE_ROOT_PASS}
            DISCOURSE_EMAIL: admin@southcla.ws
            DISCOURSE_SITENAME: Burger Shot
            DISCOURSE_HOSTNAME: forum.southcla.ws
            POSTGRESQL_ROOT_USER: postgres
            POSTGRESQL_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            POSTGRESQL_HOST: postgresql
            POSTGRESQL_PORT_NUMBER: "5432"
            DISCOURSE_POSTGRESQL_USERNAME: postgres
            DISCOURSE_POSTGRESQL_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
            DISCOURSE_POSTGRESQL_NAME: discourse
            REDIS_HOST: redis
            REDIS_PORT_NUMBER: "6379"
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            SMTP_HOST: ${SMTP_HOSTNAME}
            SMTP_PORT: "${SMTP_PORT}"
            SMTP_USER: ${SMTP_USERNAME}
            SMTP_PASSWORD: ${SMTP_PASSWORD}
            SMTP_TLS: "${SMTP_USE_TLS}"
        volumes:
            - "${DATA_DIR}/openmp/discourse:/bitnami"
        networks:
            - default
            - databases
        depends_on:
            - postgresql
            - redis
        # ports:
        #   - 80:3000
        labels:
            - traefik.docker.network=gateway
            - "traefik.frontend.rule=Host:forum.southcla.ws"
            - traefik.frontend.headers.SSLRedirect=false
            - traefik.port=3000
