version: "3.5"

networks:
    default:
        external:
            name: gateway
    database:
        driver: bridge
        internal: true

services:
    homepage:
        image: southclaws/openmp:latest
        restart: on-failure
        networks:
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=gateway
            - traefik.frontend.rule=Host:www.open.mp,open.mp,openmp.burgershot.gg
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.SSLHost=open.mp
            - traefik.frontend.redirect.regex=^https?://[a-z0-9.]+/(.*)
            - traefik.frontend.redirect.replacement=https://www.open.mp/$${1}
            - traefik.port=3000
            - com.centurylinklabs.watchtower.enable=true

    wiki:
        image: southclaws/openmp-wiki:latest
        restart: on-failure
        networks:
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=gateway
            - traefik.frontend.rule=Host:wiki.open.mp
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.SSLHost=wiki.open.mp
            - traefik.frontend.redirect.regex=^https?://[a-z0-9.]+/(.*)
            - traefik.frontend.redirect.replacement=https://wiki.open.mp/$${1}
            - traefik.port=80
            - com.centurylinklabs.watchtower.enable=true

    mybb:
        image: mybb/mybb:latest
        restart: on-failure
        volumes:
            - ${DATA_DIR}/burgershot/mybb:/var/www/html:rw
        networks:
            - database
            - default
        labels:
            - traefik.enable=false

    nginx:
        image: nginx:mainline
        restart: on-failure
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ${DATA_DIR}/burgershot/mybb:/var/www/html:ro
        labels:
            - traefik.enable=true
            - traefik.docker.network=gateway
            - traefik.frontend.rule=Host:www.burgershot.gg,burgershot.gg
            - traefik.frontend.headers.SSLRedirect=true
            - traefik.frontend.headers.SSLHost=www.burgershot.gg
            - traefik.frontend.redirect.regex=^https?://[a-z0-9.]+/(.*)
            - traefik.frontend.redirect.replacement=https://www.burgershot.gg/$${1}
            - traefik.port=80
        networks:
            - default

    postgresql:
        image: postgres:10.4
        restart: on-failure
        environment:
            POSTGRES_DB: burgershot
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: burgershot
        networks:
            - database
        volumes:
            - ${DATA_DIR}/burgershot/postgres/data:/var/lib/postgresql/data
