version: "3.5"

networks:
  default:
    external:
      name: gateway
  databases:
    driver: bridge
    internal: true

services:
  flarum:
    image: mondedie/docker-flarum:0.1.0-beta.7.1-stable
    environment:
      FORUM_URL: http://localhost
      DB_PASS: ${MARIA_PASSWORD}
      LOG_TO_STDOUT: "true"
      DEBUG: "true"
    volumes:
      - ${DATA_DIR}/openmp/flarum/assets:/flarum/app/assets
      - ${DATA_DIR}/openmp/flarum/extensions:/flarum/app/extensions
    ports:
      - 8888:8888
    networks:
      - default
      - databases
    depends_on:
      - mariadb
    labels:
      - traefik.docker.network=gateway
      - "traefik.frontend.rule=Host:tanuki.southcla.ws"
      - traefik.frontend.headers.SSLRedirect=true
      - traefik.port=8888

  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_ROOT_PASSWORD}
      MYSQL_DATABASE: flarum
      MYSQL_USER: flarum
      MYSQL_PASSWORD: ${MARIA_PASSWORD}
    volumes:
      - ${DATA_DIR}/openmp/mysql/db:/var/lib/mysql
    networks:
      - databases
    labels:
      - traefik.enable=false
